### ISSUE TITLE
Beach gantry wheel(s) cracked

### ISSUE THREAD

**Issue by petebachant** [UNH-OE/tow-tank#39]
At least one of these is cracked--see below. See #13 for some ideas for improving the system. 

![image](https://cloud.githubusercontent.com/assets/4604869/5795285/7affbcca-9f5a-11e4-9848-cc1af9d846e3.png)

**Comment by petebachant** [comment]
This became a bit worse today. I recommend addressing #58. 

![image](https://cloud.githubusercontent.com/assets/4604869/6519936/5a47d604-c389-11e4-8abe-322f88e1f29b.png)

![image](https://cloud.githubusercontent.com/assets/4604869/6519912/177a3114-c389-11e4-83a1-b4d42c6be892.png)

**Comment by amcleodUNH** [comment]
One sick day and the whole world falls apart ….

Let’s consider changing over to hard rubber with bearings.

**Comment by petebachant** [comment]
It might be helpful, while this is being worked on, to add some type of track for the wheels so a single person could move the gantry. Some v-groove wheels and a track made from angle iron would be pretty cheap.

**Comment by petebachant** [comment]
Fixed on March 13.
