### ISSUE TITLE
Beach Repair

### ISSUE THREAD

**Issue by amcleodUNH** [UNH-OE/tow-tank#50]
The right hand tooth of the beach has structural failure in 2 pieces of the fiberglass angle framework. Beach has been lifted and the tooth pulled for repair. Beach is to remain out at this time until repair complete. Additionally, 3 6x6 beams must be purchased for supporting beach when stowed in the lifted position.

**Comment by petebachant** [comment]
@amcleodUNH, when do you guys think this will be done? I need to have the beach in for some experiments starting Feb 1.

**Comment by petebachant** [comment]
Done. Closing.
